export const WAIVER_LABELS = {
  p1_print_name: 'Printed name(s)',
  p1_date: 'Waiver date',
  p1_signature: 'Signature (page 1)',
  p1_email: 'Email',
  minor_1: 'Minor child 1',
  minor_2: 'Minor child 2',
  minor_3: 'Minor child 3',
  minor_4: 'Minor child 4',
  waiver_name: 'Name (Poker Ride waiver)',
  other_party_name: 'Other contracting party (spouse / parent)',
  address: 'Address',
  phone_home: 'Phone – home',
  phone_work: 'Phone – work',
  phone_cell: 'Phone – cell/other',
  child_1_name: 'Child / ward 1',
  child_1_age: 'Child / ward 1 age',
  child_1_dob: 'Child / ward 1 date of birth',
  child_2_name: 'Child / ward 2',
  child_2_age: 'Child / ward 2 age',
  child_2_dob: 'Child / ward 2 date of birth',
  initial_risks: 'Initials – risks of equine activities',
  initial_waiver_release: 'Initials – waiver & indemnification',
  emergency_name: 'Emergency contact – name',
  emergency_phone: 'Emergency contact – phone',
  emergency_relationship: 'Emergency contact – relationship',
  rep_1_initial: 'Initials – I am 18 or over',
  rep_1_over_18: 'Confirmed – I am 18 or over',
  rep_2_initial: 'Initials – sound mind',
  rep_2_sound_mind: 'Confirmed – sound mind, not impaired',
  rep_3_initial: 'Initials – read entire document',
  rep_3_read_document: 'Confirmed – read entire document',
  rep_4_initial: 'Initials – valid & binding',
  rep_4_binding: 'Confirmed – valid & binding',
  rep_5_initial: 'Initials – giving up legal rights',
  rep_5_legal_rights: 'Confirmed – giving up legal rights',
  rep_6_initial: 'Initials – court may find waiver',
  rep_6_court_waiver: 'Confirmed – court may find waiver',
  rep_7_initial: 'Initials – information is true',
  rep_7_info_true: 'Confirmed – information is true',
  p5_signature: 'Signature (final page)',
  p5_print_name: 'Printed name (final page)',
  p5_date: 'Date (final page)',
  spouse_signature: 'Signature – other contracting party',
  spouse_date: 'Date – other contracting party',
  spouse_print_name: 'Printed name – other contracting party',
  spouse_print_date: 'Printed date – other contracting party',
  aea_guidelines_agreed: 'Read & agreed to AEA Safety Guidelines & Rules',
  entry_type: 'Waiver form used',
  _signed_at: 'Signed at (server time)',
  _signed_ip: 'Signed from IP',
  _stable_signer: 'Stable representative signature',
};
export const SIGNATURE_KEYS = ['p1_signature', 'p5_signature', 'spouse_signature', '_stable_signer'];
